# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Left/Right block"
  description: Content that can be arranged left-right or right-left
  icon: art_track
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: bookshop:generic/heading
  display_social_icons: true
  show_social_icons_note: true
  text:
  buttons: [bookshop:generic/button]
  icons: [bookshop:generic/labelled-icon]
  image: bookshop:generic/image
  map: bookshop:simple/google-map-embed
  image_alignment: Left
  image_padding: false
  color_group: "" 


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading:
    _bookshop_name: generic/heading
    eyebrow_headline: Let your features shine
    primary_heading: A featured icons left right block
  display_social_icons: true
  text: >-
    This is a simple yet powerful block to display not only your location by using Google Maps, but also any other contact details you wish to share with your customers.
  buttons:
    - url: "#"
      open_in_new_tab: false
      text: "Button text"
      variant: "primary"
      disabled: false
      arrow: "right"
      onclick: 
  icons:
    - _bookshop_name: generic/labelled-icon
      arrangement: inline
      text: Great customer service
      icon:
        _bookshop_name: generic/hero-icon
        hero_icon_name: academic-cap
        icon_size: small
        icon_type: solid
        rounded_border: true
        theme_color: true
  image_alignment: Left
  color_group: "" 
  image: 
    _bookshop_name: generic/image
    image_path: https://placekitten.com/300/500
    image_alt: A cute kitten
  map:
    _bookshop_name: simple/google-map-embed
    latitude: 37.782046
    longitude: -122.4514212
    zoom_level: 9



# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  image_alignment:
    type: select
    options:
      values:
        - Left
        - Right 