# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Left/Right - Featured icons"
  description: Represents key features or services in a nice iconed layout
  icon: art_track
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    id:
    heading: bookshop:generic/heading!
    icons:
    buttons: [bookshop:generic/button!]
    image: bookshop:generic/image!
  styles:
    image_alignment: Left
    color_group: "" 


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    heading:
      _bookshop_name: generic/heading
      eyebrow_headline: Let your features shine
      primary_heading: A featured icons left right block
    icons:
      - hero_icon_name: face-smile
        icon_text: 100% Happy customer reviews
        icon_type: outline
      - icon_path: /assets/images/icons/social/youtube.svg
        icon_text: Great customer service
        icon_type: outline
      - hero_icon_name: star
        icon_text: Outstanding product reviews
        icon_type: solid
    buttons:
      - _bookshop_name: generic/button
        url: "#"
        open_in_new_tab: false
        text: "Book Now"
        variant: "primary"
        disabled: false
        arrow: "right"
        onclick: 
    image: 
      bookshop: generic/image
      image_path: https://placekitten.com/300/500
      image_alt: A cute kitten
  styles:
    image_alignment: Left
    color_group: "" 


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  icon_path:
    type: image
  image_alignment:
    type: select
    options:
      values:
        - Left
        - Right 
  icons:
    type: array
    comment: Recommended to have no more than three icons here
    options:
      structures: _structures.icon_types
_structures:
  icon_types:
    values:
      - label: Hero Icon
        value:
          hero_icon_name: academic-cap
          icon_type:
          icon_text:
        _inputs:
          icon_type:
            comment: Choose outline if you want lines to be filled with color and solid if you want the whole image filled with color
            type: choice
            options:
              allow_empty: false
              values:
                - solid
                - outline
      - label: Custom Icon
        value:
          icon_path:
          icon_type:
          icon_text:
        _inputs:
          icon_type:
            comment: Choose outline if you want lines to be filled with color and solid if you want the whole image filled with color
            type: choice
            options:
              allow_empty: false
              values:
                - solid
                - outline
          icon_path:
            type: image