# Metadata about this component, to be used in the CMS
spec:
  structures:
    - hero_blocks
  label: "Hero - Simple"
  description: A simple heading block to be used as a hero
  icon: feed
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    heading: bookshop:generic/heading!
  styles:
    content_alignment: center
    color_group: "" 


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  styles:
    content_alignment: center
    color_group: "" 
  content:
    heading:
      _bookshop_name: generic/heading
      eyebrow_headline: a small business template
      eyebrow_headline_hierarchy: h2
      primary_heading: Empower Your Business with This Brilliant Template
      primary_heading_hierarchy: h1

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: