# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Left/Right - Featured map"
  description: Display your contact details and a map
  icon: contact_phone
  tags: ['contact', 'content-block', 'left-right']

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    id:
    display_social_icons: true
    show_note: true
    heading: A contact block
    description: This is a simple yet powerful block to display not only your location by using Google Maps, but also any other contact details you wish to share with your customers.
    contact_details:
      - text: 'Email address: mybusiness@business.com'
        hero_icon_name: envelope
    map: bookshop:simple/google-map-embed
    buttons: [bookshop:generic/button]    
  styles:
    map_alignment: Left
    color_group: "" 


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    display_social_icons: true
    show_note: false
    heading: A contact block
    content: Content
    contact_details:
      - text: 'Email address: mybusiness@business.com'
        hero_icon_name: envelope
    map: bookshop:simple/google-map-embed
    buttons: [bookshop:generic/button]
  styles:
    map_alignment: Left
    color_group: "" 

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  contact_details:
    type: array
    options:
      structures:        
        values:
          - label: Email    
            icon: mail_outline      
            value:
              _type: Email
              text: 'Email address: mybusiness@business.com'
              hero_icon_name: envelope
          - label: Phone
            icon: call
            value:
              _type: Phone
              text: 'Phone number: 312 325 326'
              hero_icon_name: phone
          - label: Address 
            icon: location_on        
            value:
              _type: Address
              text: 'Address: 1 Fake St, Faketown'
              hero_icon_name: map-pin
          - label: Opening hours
            icon: schedule
            value:
              _type: Hours
              text: 'Opening hours: 9-5pm, Monday to Friday'
              hero_icon_name: clock
          - label: Custom
            icon: person
            value:
              _type: Custom
              text: ''
              hero_icon_name: ''
  map_alignment:
    type: select
    options:
      values:
        - Left
        - Right  
  description:
    type: markdown  
    