# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Gallery"
  description: A grid layout of images
  icon: collections
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  show_note: true
  images: [bookshop:generic/image]
  button:
    text: Load More
    variant: primary

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  images:
    - bookshop:generic/image
    - bookshop:generic/image
    - bookshop:generic/image
    - bookshop:generic/image
    - bookshop:generic/image

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  images:
    comment: The images should be square in shape
  variant:
    type: select
    options:
      values:
        - primary
        - secondary