# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Grid - Gallery Images"
  description: A grid layout of images with supporting information
  icon: collections
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    id:
    heading: bookshop:generic/heading!
    description: Description text to compliment the block
    gallery: bookshop:simple/gallery!
  styles:
    color_group: "" 

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    heading:
      _bookshop_name: generic/heading
      eyebrow_headline: EYEBROW HEADLINE
      primary_heading: List your services and products
    description: >-
      Whether your business is a restaurant, a barber shop, a gym, or a café, our
      small business template has you covered. Add your services to the list
      below, as many as you like, and let people contact you or book now.
    gallery: bookshop:simple/gallery
  styles:
    color_group: "" 

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: textarea